#!/bin/bash
echo "Zaganjam flake8 preverjanje..."
flake8 main.py
if [ $? -ne 0 ]; then
  echo "Fail Koda ni ustrezno oblikovana – commit zavrnjen."
  exit 1
fi
echo "OK Preverjanje uspešno – commit dovoljen."
exit 0
